default: &default
  title: Exchanger
  host: localhost:3000

  mailer:
    # For localhost postfix
    smtp_settings:
      address: localhost
      port: 587
      enable_starttls_auto: false
      #domain:
      #user_name:
      #password:
      #authentication:
    default_options:
      from: no-reply@miako.org
    default_url_options:
      host: localhost:3000

  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

  elasticsearch:
    host: localhost:9200

development:
  <<: *default
  admin_emails:
    - udonmai@kyoto-u.ac.jp

test:
  <<: *default
  admin_emails:
    - admin@example.com

production:
  <<: *default
  admin_emails:
    - wen@db.soc.i.kyoto-u.ac.jp
